const SERVICE_LEVEL_STANDARD = 'Standard'
const SERVICE_LEVEL_GUARANTEED = 'Guaranteed'
const SERVICE_LEVEL_STANDARD_VOL = 'Standard - Volume'
const SERVICE_LEVEL_GUARANTEED_TRUCKLOAD = 'Guaranteed - Truckload'

module.exports = {
    SERVICE_LEVEL_STANDARD,
    SERVICE_LEVEL_GUARANTEED,
    SERVICE_LEVEL_STANDARD_VOL,
    SERVICE_LEVEL_GUARANTEED_TRUCKLOAD,
}
